# Generated by Django 3.1.6 on 2021-03-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0004_auto_20210305_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
